name: mahall_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter: 
    sdk: flutter
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  curved_navigation_bar: ^1.0.6
  lottie: ^3.0.0
  share_plus: ^10.1.2
  http: ^0.13.6
  path_provider: ^2.1.5

  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1

  app_settings: ^5.1.1
  package_info_plus: ^8.1.1
  connectivity_plus: ^6.1.0
  toastification: ^2.3.0
  shimmer: ^3.0.0
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  permission_handler: ^11.3.1
  flutter_qiblah: ^3.0.4
  device_info_plus: ^9.1.2
  adhan: ^2.0.0+1
  geolocator: ^13.0.2


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  generate : true

  assets:
    - assets/logo/
    - assets/images/
    - assets/animations/
    - lib/l10n/
flutter_intl:
  enabled: true
